### ISSUE TITLE
Sugestão de Melhoria

### ISSUE THREAD

**Issue by Silmunia** [LidyIfce/SwiftChallenge#1]
**Arquivo:**
estante.swift

**Sugestão:**
Adaptar a atual funcionalidade de armazenar e adicionar filmes que está usando um Array para usar um Set. Como não há motivo para um usuário adicionar o mesmo filme várias vezes na lista, um Set parece mais adequado para ter elementos únicos.

**Comment by lidianegb** [comment]
Obrigada pela dica. Estamos trabalhando para que os filmes não se repitam ao ser adicionados. No caso o Set não é a melhor solução pois a classe filme possui muitos atributos e pra duas instâncias de filme serem consideradas iguais, todos os atributos devem ser iguais. No nosso caso, a cada inserção de filmes um código único é gerado para aquele filme, então nunca vai existir instâncias iguais de filme, pois elas iriam se diferenciar pelo código. Estamos trabalhando pra tratar a entrada de nome de filme. Toda vez que for digitado um novo nome, vamos verificar se já não existe filme adicionado com aquele nome, caso exista ele apresenta a mensagem e não adiciona.

Obrigada!!
