### ISSUE TITLE
Feedback: Recomendação de Filmes

### ISSUE THREAD

**Issue by kellyanenogueira1** [LidyIfce/SwiftChallenge#12]
**Arquivo:** Estante.swift e Filme.swift
**Função:** gerarRecomendação()

**Sugestão:** 
Olá! Percebemos que, quando é feita a recomendação de filmes é baseado em um Array de filmes não assistidos. Nossa sugestão seria alterar esta recomendação de acordo com um gênero mais assistido, ficando mais adequado ao perfil de usuário. No caso, teria que adicionar um atributo gênero a class Filme e um novo array que pudesse guardar o gênero mais assistido.

_By Kellyane Nogueira e Elias Ferreira_

**Comment by lidianegb** [comment]
Oi pessoal. Obrigada pela dica.
A ideia do Movie Recommendation é que o usuário salve uma lista com filmes que ele tem o desejo de assistir, ou que alguém recomendou que ele assistisse. Então, quando ele assiste um filme de sua lista ela é marcada como assistida e não vai mais aparecer na tela dele como recomendação quando ele quiser assistir outro filme. Como na lista estão filmes que ele tem o desejo de assistir achamos que recomendar pelo gênero mais assistido limita a lista. Até estamos cogitando colocar um atributo que guarde o gênero do filme, mas só por informação mesmo, até pra ter como ver lista de filmes por gênero, por exemplo.

Mas obrigada pela dica!!! :D
