### ISSUE TITLE
Sugestão de Melhoria

### ISSUE THREAD

**Issue by ronaldogomes96** [LidyIfce/SwiftChallenge#3]
Dupla: Ronaldo / Bia
Arquivo:
estante.swift
Sugestão:
Trocar o tipo de retorno da função gerarRecomendacao de (Int, String) para somente (String) e no return colocar
return " \(cod) -  \(nomeFilme) "
Dessa forma economizaria dados e a mensagem na tela não teria aspas nem parênteses.

**Comment by lidianegb** [comment]
Oie, resolvi retornar uma string apenas com o nome do filme, acho que ficou melhor a visualização.
obrigada pela dica!

**Comment by lidianegb** [comment]
![photo_2020-04-02 16 22 32](https://user-images.githubusercontent.com/39997529/78292942-35b83000-74fe-11ea-86c8-ecaea222eb8d.jpeg)
