### ISSUE TITLE
Sugestão de Melhoria

### ISSUE THREAD

**Issue by eduregis** [LidyIfce/SwiftChallenge#7]
Dupla:
L. Eduardo e Larissa

Arquivo:
estante.swift

Melhoria: Garantir unicidade de um elemento numa lista utilizando um validador ou uma estrutura que não aceita duplicatas (como um set) seria uma boa para evitar o usuário insira o mesmo filme várias vezes. Esse erro ficaria mais comum a medida que a “watch list” fosse crescendo. Outra sugestão de melhoria seria limpar a tela após cada interação do usuário. Como é uma emulação de interface gráfica por terminal, seria legal o usuário ver apenas os dados atuais.

**Comment by lidianegb** [comment]
Olá, desde já agradeço pela contribuição. 
Quando a inserção de nomes repetidos, nós já tínhamos pensado e estamos trabalhando nisso. 
Sobre limpar o terminal tbm estávamos querendo implementar isso, porém não tínhamos encontrado uma função para tal. Então eu vi no código do projeto de vcs que lá tem uma função pra limpar o terminal e nós decidimos pegar ela pro nosso código haha :D
Obrigada!
